# This file is for render site varibles and plugins
# don't remove this file.
# The presence of this file is for compatibility with Blogdown and Forestry.
#
# The actual configuration files are stored in the `config/_default/` folder.


######################### site variables ##############################
# customize your color and font from here.
[params.variables]
primary_color = "#0EA5E9"
text_color = "#64748b"
text_color_dark = "#0f172a"
body_color = "#ffffff"
border_color = "#e2e8f0"
black = "#0f172a"
white = "#ffffff"
light = "#f8fafc"

# font variable
# Give your font name from google font. add font weight using ":wght@" and separate by ";"
# example: "Work Sans:wght@400;500;600"
primary_font = "Inter:wght@400;500;600;700"
primary_font_type = "sans-serif" # [serif/sans-serif]
icon_font = "Font Awesome 5 Free"


############################# Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/fontawesome.min.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/brands.min.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/solid.min.css"


# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.slim.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
# [[params.plugins.js]]
# link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/js/all.min.js"
# attributes = "crossorigin='anonymous' defer='defer' data-search-pseudo-elements"