######################## default configuration ####################
baseURL = "https://www.ziljtech.com/"
title = "ZILJ Tech Private Limited"
theme = "bigspring-light"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# post pagination
paginate = "3"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = ""
# google analytics
googleAnalytics = ""

# SEO
enableRobotsTXT = true

# Sitemap
[sitemap]
  changefreq = "weekly"
  priority    = 0.5
  filename    = "sitemap.xml"

# unsafe html
[markup.goldmark.renderer]
unsafe = true

# Minify in production
[minify]
  disableXML = false