############################# English ############################
[en]
languageName = "En"
title = "ZILJ Tech"
contentDir = "content/english"
weight = 1
########### footer content ##########
footer_menu_left = "Quick Links"
footer_menu_middle = "Legal"
footer_menu_right = "Legal"
footer_content = "236/16, ZILJ TECH PRIVATE LIMITED<br>Cherai Beach Road, Pallippuram<br>Ernakulam, Kerala — 683514<br><br>ziljtech@gmail.com<br>+91 9567668085"
# copyright
copyright = "© 2024 ZILJ Tech Private Limited. All Rights Reserved."



############################# Deutsch ############################
