############################# English ############################
[en]
languageName = "En"
title = "ZILJ Tech"
contentDir = "content/english" # content/english
weight = 1
########### footer content ##########
footer_menu_left = "Company"
footer_menu_middle = "Company"
footer_menu_right = "Support"
footer_content = "ziljtech@gmail.com \n \n+91 9567668085"
# copyright
copyright = "Design By ZILJ Tech "



############################# Deutsch ############################
