# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About Us"
url = "/"
weight = 2


[[main]]
name = "Contact"
url = "contact/"
weight = 4


# footer menu left
[[footer_middle]]
name = "About Us"
url = "#"

[[footer_middle]]
name = "Quick Start"
url = "#"







# footer menu right
[[footer_right]]
name = "Privacy Policy"
url = "privacy-policy/"

[[footer_right]]
name = "Terms & Conditions"
url = "terms-conditions/"

